DROP TABLE pacjent;
DROP TABLE lek;
DROP TABLE recepta;

CREATE TABLE IF NOT EXISTS pacjent (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(250) NOT NULL,
    LAST_NAME VARCHAR(250) NOT NULL,
    PESEL VARCHAR(250) NOT NULL,
    NR_UBEZPIECZENIE VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS lek (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(250) NOT NULL,
    PRODUCENT VARCHAR(250) NOT NULL,
    ILOSC INT NOT NULL
);

CREATE TABLE IF NOT EXISTS recepta (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PESEL_PACJENTA VARCHAR(250) NOT NULL,
    DATA_WAZNOSCI DATE NOT NULL
);

